// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

#nullable disable

namespace rpgapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221211184759_Characters")]
    partial class Characters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RpgApi.Models.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = "9f714da3-bdd8-4611-8b1e-db6fc81275f4",
                            Class = 8,
                            Defence = 15,
                            Health = 100,
                            Intelligence = 30,
                            Name = "Benag",
                            Strength = 10
                        },
                        new
                        {
                            Id = "354af967-b201-4749-baf4-faf113a24c06",
                            Class = 2,
                            Defence = 20,
                            Health = 150,
                            Intelligence = 15,
                            Name = "Amrier",
                            Strength = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
